import { Outfit } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./Provider";

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap", 
});

export const metadata = {
  title: "Learnify Ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>


      
    <html lang="en">
      <body className={clsx(outfit.className, "mdl-js")}>
        <Provider>
        {children}
        </Provider>
  
      </body>
    </html>
    
    </ClerkProvider>
  );
}
